DROP PROCEDURE IF EXISTS voorwerpRubriekInsert;
DROP PROCEDURE IF EXISTS voorwerpInsert;
DROP PROCEDURE IF EXISTS fileInsert;
DROP PROCEDURE IF EXISTS rubriekInsert;
DROP PROCEDURE IF EXISTS KeyWordInsert;
DROP PROCEDURE IF EXISTS KeyWordLinkInsert;
DROP PROCEDURE IF EXISTS getKeyWordId;